[package]
name = "solidity-fn-collision"
version = "0.3.0"
authors = ["0age <0age@protonmail.com"]
license = "MIT"
edition = "2021"

[dependencies]
hex = "0.4"
ocl = "0.19"

[profile.release]
opt-level = 3
lto = "fat"
strip = true
panic = "abort"
codegen-units = 1

[features]
default = []
